### ISSUE TITLE
E11000 duplicate key error index pymongo

### ISSUE THREAD

**Issue by thosuperman** [sentinelanalytics/facebook-scraper-py#1]
Dear sentinelanalytics,

I got the error "E11000 duplicate key error index pymongo" when trying to use your source code.

P/S: I'm very new with Python and I see you source code is very helpful. Would you please guide me how to export the scraper data into CSV file, with file name is page_id (such as 97041406678_posts.csv, 97041406678_comments.csv ... )?

**Comment by torresjeff** [comment]
Hi @thosuperman,

We've been getting the errors too, and this is something we're looking to fix. The script is far from perfect, so right now what you could do is simply run it again. Pull requests are welcome :)

As for exporting the data to CSV, you could write a script yourself or if you want an easier way you could use [Mongo Express](https://github.com/mongo-express/mongo-express), which is a free GUI for Mongo. It has options to export files to CSV, JSON, etc. I think you could run some queries and export the result (not sure about this)
